version: "3.8"

services:

  db:

    image: postgres

    ports:
      - 5432:5432

  ml:

    build:
      context: ./ml

    ports:
      - 5000:5000
      - 6006:6006
      
    command: python /usr/src/app/server.py
