version: "3"

services:

  alice:
    image: php-fpm
    restart: unless-stopped
    container_name: alice
    command: node alice/index.js
    expose:
      - 3000
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www
      - ../alice:/var/www/alice
    environment:
      CONTAINER_ROLE: echo
    ports:
      - 3000:3000
